# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31f8f9f1accc568a729001dca300cacaf90efaf32ec394055efe4805424cb2adc11e3e131bc9b7b98178170e9550b2b8ae9cf92c0c7e48453df79a3dcb89f927

test:
  secret_key_base: 1faccca8bd1cf90a4f587c49d9263049854d9c171eb0afd347b8afc9a50b91c8b0754bea25976510bca69af1d35b5e235d4ee979569e07254aef4b8959b70f90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
